In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
U, s, Vt = np.linalg.svd(A)

In [4]:
print("Left Singular Vectors (U):")
print(U)
print("Singular Values (s):")
print(s)
print("Right Singular Vectors (Vt):")
print(Vt)

Left Singular Vectors (U):
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular Values (s):
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
Right Singular Vectors (Vt):
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
